#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

install_cmd() {
  local DOKKU_TOR_ROOT="$DOKKU_ROOT/.tor"
  local DOKKU_TOR_OPTIONS="$DOKKU_TOR_ROOT/OPTS"
  local DOKKU_TOR_IMAGE_REPO="rdsubhas/tor-privoxy-alpine"
  local DOKKU_TOR_IMAGE_VERSION="latest"
  local DOKKU_TOR_IMAGE="${DOKKU_TOR_IMAGE_REPO}:${DOKKU_TOR_IMAGE_VERSION}"

  if [[ ! -f "$DOKKU_TOR_OPTIONS" ]]; then
    echo "export DOKKU_TOR_IMAGE=$DOKKU_TOR_IMAGE" > "$DOKKU_TOR_OPTIONS"
    echo "export DOKKU_TOR_CONTAINER_NAME=$DOKKU_TOR_CONTAINER_NAME" >> "$DOKKU_TOR_OPTIONS"
  fi

  [[ -f "$DOKKU_TOR_OPTIONS/OPTS" ]] && source "$DOKKU_TOR_OPTIONS/OPTS"
  mkdir -p "$DOKKU_TOR_ROOT"
  docker pull "$DOKKU_TOR_IMAGE"
}

install_cmd "$@"
